# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="skaro"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras github grails history osx)

source $ZSH/oh-my-zsh.sh

# aliases
alias vi=vim
alias sqlp="sqlplus system/canoe@'(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=oraclehost)(PORT=1521)))(CONNECT_DATA=(SID=devvm)))'"
alias ssha="ssh -p 10022 root@ammi.viviotech.net"

# home
# export GRAILS_HOME=/usr/local/grails-2.0.4
# export GROOVY_HOME=/usr/local/groovy
# export GRADLE_HOME=/usr/local/gradle
# export SCALA_HOME=/usr/local/scala
export M2_HOME=/usr/local/maven
export DYLD_LIBRARY_PATH=/usr/local/instantclient
export ORACLE_SID=devvm
# export JAVA_HOME=`/usr/libexec/java_home -v '1.7*'`

# Customize to your needs...
# export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:$M2_HOME/bin:/usr/local/groovy/bin:/usr/local/mongo/bin:$GRADLE_HOME/bin:$DYLD_LIBRARY_PATH

#functions
# function tmate { open -a TextMate $1; }
# export -f tmate

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/michaelmunhall/.gvm/bin/gvm-init.sh" ]] && source "/Users/michaelmunhall/.gvm/bin/gvm-init.sh"
